name: Waka Readme

on:
  schedule:
    # Cập nhật mỗi 2 tiếng
    - cron: '0 */2 * * *'
    # Reset đầu tuần: 0h UTC thứ Hai = 7h sáng VN
    - cron: '0 0 * * MON'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update README with WakaTime Stats
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          LANG_COUNT: 2
          RANGE: this_week
